name: virtual_aquarium
description: A virtual aquarium app with animated fish and SQLite storage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  # Database (Local Storage)
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # UI & Animations
  flutter_lints: ^5.0.0
  fl_chart: ^0.70.2
  provider: ^6.0.5

  # Preferences
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter Rules
  lints: ^5.1.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
